# Generated by Django 5.2.7 on 2025-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='nivel',
            field=models.CharField(default='Auxiliar', max_length=20),
        ),
    ]
